version: "1.0"
info:
  model: int-scaffold
packages:
- name: Selvi_DADA_DemoProject
  gitServerName: selvi_demo
  gitUrl: https://github.com/AvudaiSelvi/Selvi_DADA_DemoProject
  gitUsername: AvudaiSelvi
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: softwareag
- name: WmTNMigration
  version: "1.0"
  gitServerName: SelviGitHub
  gitUrl: https://github.com/AvudaiSelvi
  gitUsername: AvudaiSelvi
  gitBranch: main
services:
- serviceName: project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: Selvi_DADA_DemoProject
    version: "1.0"
- serviceName: project.selvi_dada_demo.integrations:generateQuotation
  packages:
  - name: Selvi_DADA_DemoProject
    version: "1.0"
- serviceName: project.selvi_dada_demo.integrations:getCustomerById
  packages:
  - name: Selvi_DADA_DemoProject
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.io:bytesToStream
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: project.selvi_dada_demo.integrations:getProductById
  packages:
  - name: Selvi_DADA_DemoProject
    version: "1.0"
- serviceName: pub.string:isNumber
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.math:multiplyFloats
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.math:subtractFloats
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: project.selvi_dada_demo.integrations:DB_Connection
  packages:
  - name: Selvi_DADA_DemoProject
    version: "1.0"
- serviceName: project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:db_con
  packages:
  - name: Selvi_DADA_DemoProject
    version: "1.0"
- serviceName: project.selvi_dada_demo.integrations:GetAllIODetails
  packages:
  - name: Selvi_DADA_DemoProject
    version: "1.0"
  - name: WmTNMigration
    version: "1.0"
- serviceName: WmTNMigration.wm.b2b_io_wrapper:getAllwmioProjects
  packages:
  - name: WmTNMigration
    version: "1.0"
- serviceName: pub.io:streamToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.json:jsonStringToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
configurationVariables:
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : avse_db
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : MSSQL
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : ""
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "true"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "1433"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}RYx1IM0D4+FXZl9TWOJFeiQI/2qi+E6z5HYLwnEDsYY="
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : localhost
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Selvi_DADA_DemoProject.project.selvi_dada_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : avse
